# Sample .travis.yml for R projects

language: r
sudo: false
cache: packages

r_packages:
  - gpclib

env:
 global:
   - RGL_USE_NULL=TRUE

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
use_bioc: true
bioc_required: true
